[package]
name = "uplc"
description = "Utilities for working with Untyped Plutus Core"
version = "0.0.12"
edition = "2021"
repository = "https://github.com/txpipe/aiken/crates/uplc"
homepage = "https://github.com/txpipe/aiken"
license = "Apache-2.0"
authors = ["Lucas Rosa <x@rvcas.dev>", "Kasey White <kwhitemsg@gmail.com>"]

exclude = ["test_data/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptoxide = "0.4.2"
flat-rs = { path = "../flat", version = "0.0.10" }
hex = "0.4.3"
pallas-codec = { git = "https://github.com/txpipe/pallas" }
pallas-primitives = { git = "https://github.com/txpipe/pallas" }
peg = "0.8.0"
pretty = "0.11.3"
thiserror = "1.0.31"

[dev-dependencies]
hex = "0.4.3"
proptest = "1.0.0"

[features]
unstable = []
