[package]
name = "uplc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
flat = { path = "../flat" }
hex = "0.4.3"
strum = "0.24.0"
strum_macros = "0.24.0"
thiserror = "1.0.31"
