[package]
name = "uplc"
description = "Utilities for working with Untyped Plutus Core"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/txpipe/aiken/crates/uplc"
homepage = "https://github.com/txpipe/aiken"
license = "Apache-2.0"
authors = ["Lucas Rosa <x@rvcas.dev>", "Kasey White <kwhitemsg@gmail.com>"]

exclude = ["test_data/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flat = { path = "../flat", version = "0.0.1" }
hex = "0.4.3"
peg = "0.8.0"
strum = "0.24.0"
strum_macros = "0.24.0"
thiserror = "1.0.31"
