[package]
name = "aiken-lang"
version = "0.0.16"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
internment = "0.7.0"
miette = "5.2.0"
vec1 = "1.8.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
